Last time, linear regression was good enough to figure out where the dividing line runs. Now, what if there are multiple lines, or lines with wild curves? Time for gradient descent!

In [18]:
from torch.utils.data import Dataset, DataLoader
import torch as tc

class GradientDescender:
    def __init__(self,initial_dataset:Dataset):
        self.dataset = initial_dataset

NUMBER_OF_FEATURES = 4

class GradientDataset(Dataset):
    def __init__(self,data,labels):
        super().__init__()
        self.features:tc.Tensor = tc.tensor(data,dtype=tc.float32)
        self.labels:tc.Tensor = tc.tensor(labels,dtype=tc.int8)
    
    def __getitem__(self,index) -> tuple[tc.Tensor, tc.Tensor]:
        datapoint = self.features[index]
        datalabel = self.labels[index]
        return datapoint, datalabel

    def __len__(self) -> int:
        return self.labels.shape[0]

In [20]:
from numpy import array
data = array([[ 0.77, -1.14],
       [-0.33,  1.44],
       [ 0.91, -3.07],
       [-0.37, -1.91],
       [-0.63, -1.53],
       [ 0.39, -1.99],
       [-0.49, -2.74],
       [-0.68, -1.52],
       [-0.1 , -3.43],
       [-0.05, -1.95],
       [ 3.88,  0.65],
       [ 0.73,  2.97],
       [ 0.83,  3.94],
       [ 1.59,  1.25],
       [ 1.14,  3.91],
       [ 1.73,  2.8 ],
       [ 1.31,  1.85],
       [ 1.56,  3.85],
       [ 1.23,  2.54],
       [ 1.33,  2.03]])
labels = array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

dataset = GradientDataset(data,labels)

train_loader = DataLoader(dataset=dataset, batch_size=10, shuffle=True)

20
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.int8)
tensor([[ 0.7700, -1.1400],
        [-0.3300,  1.4400],
        [ 0.9100, -3.0700],
        [-0.3700, -1.9100],
        [-0.6300, -1.5300],
        [ 0.3900, -1.9900],
        [-0.4900, -2.7400],
        [-0.6800, -1.5200],
        [-0.1000, -3.4300],
        [-0.0500, -1.9500],
        [ 3.8800,  0.6500],
        [ 0.7300,  2.9700],
        [ 0.8300,  3.9400],
        [ 1.5900,  1.2500],
        [ 1.1400,  3.9100],
        [ 1.7300,  2.8000],
        [ 1.3100,  1.8500],
        [ 1.5600,  3.8500],
        [ 1.2300,  2.5400],
        [ 1.3300,  2.0300]])
(tensor([ 0.7700, -1.1400]), tensor(0, dtype=torch.int8))


In [1]:

class LogisticRegression(tc.nn.Module):
    def __init__(self,feature_count:int):
        super().__init__() #Magic incantation to ensure it's a Module.
        self.l_linear:tc.nn.Linear = tc.nn.Linear(in_features=feature_count, out_features=1)

    def forward(self, x):
        logit = self.l_linear(x)
        probabilities = tc.sigmoid(logit)



model = LogisticRegression(2)
tc.optim.SGD(model.parameters(),lr = 0.05)
epochs = 25 #Let's split the difference for now~ 
for epoch in range(epochs):
    model.train()
    for batch_id, (features,label) in enumerate(train_loader):
        print(f"e ({epoch}) b ({batch_id})")
        out = model(features)



IndentationError: expected an indented block after class definition on line 1 (1369685168.py, line 3)

In [4]:
class DunderExample:
    def __init__(self):
        print("Called the _init_ dunder.")

    def __call__(self,value:int):
        print(f"Called _call_ dunder, with value {value}")
    
    def __getitem__(self,name):
        if isinstance(name,tuple):
            print(f"Called _getitem_ dunder, with coordinates {name}")
        else:
            print(f"Called _getitem_ dunder, with index {name}")

example = DunderExample()
example(1234)

example[9]
example[1,2]

Called the _init_ dunder.
Called _call_ dunder, with value 1234
Called _getitem_ dunder, with index 9
Called _getitem_ dunder, with coordinates (1, 2)
